WebApp/Models/EmployeeStatisticType.cs
namespace WebApp.Models
{
    public enum EmployeeStatisticType
    {
        Error,
        EmployeeCount,
        AverageAge
    }
}

WebApp/Models/EmployeeViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace WebApp.Models
{
    public class EmployeeViewModel
    {
        public int? Id { get; set; }

        [Display(Name = "Имя")]
        [Required(ErrorMessage = "Поле должно быть установлено")]
        [StringLength(maximumLength: 50, MinimumLength = 3, ErrorMessage = "Длина строки должна быть от 3 до 50 символов")]
        public string FirstName { get; set; }
    
        [Display(Name = "Фамилия")]
        [Required(ErrorMessage = "Поле должно быть установлено")]
        [StringLength(maximumLength: 50, MinimumLength = 3, ErrorMessage = "Длина строки должна быть от 3 до 50 символов")]
        public string LastName { get; set; }

        [Display(Name = "Отчество")]
        [StringLength( maximumLength:50 ,ErrorMessage = "Длина строки должна быть до 50 символов")]
        public string Patronymic { get; set; }

        [Display(Name = "Возраст")]
        [Range(0, 130, ErrorMessage = "Недопустимый Возраст")]
        public int Age { get; set; }
    }
}

WebApp/Controllers/EmployeeController.cs
using AOPenenzaTest.BLL.AbstractEmployeeService;
using AOPenenzaTest.BLL.AbstractEmployeeService.DTO;
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly IEmployeeCRUDService _employeeServiceCRUD;
        private readonly IMapper _mapper;

        public EmployeeController(
            IEmployeeCRUDService employeeServiceCRUD,
            IMapper mapper)
        {
            _employeeServiceCRUD = employeeServiceCRUD;
            _mapper = mapper;
        }
        // GET: index
        public ActionResult Index()
        {
            return View();
        }

        // GET: Employee
        public async Task<ActionResult> List()
        {
            var employeeDTO = await _employeeServiceCRUD.GetAllAsync();

            return View(_mapper.Map<IEnumerable<EmployeeDTO>, IEnumerable<EmployeeViewModel>>(employeeDTO));
        }

        // GET: Employee/Details/5
        public async Task<ActionResult> Details(int id)
        {
            var employeeDTO = await _employeeServiceCRUD.GetByIdAsync(id);
            return PartialView(_mapper.Map<EmployeeDTO, EmployeeViewModel>(employeeDTO));
        }

        // GET: Employee/Create
        public ActionResult Create()
        {
            var newEmployee = new EmployeeViewModel();

            return PartialView(newEmployee);
        }

        // POST: Employee/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,FirstName,LastName,Patronymic,Age")] EmployeeViewModel employee)
        {
            if (ModelState.IsValid)
            {
                var employeeDTO = _mapper.Map<EmployeeViewModel, EmployeeDTO>(employee);
                var result = await _employeeServiceCRUD.AddAsync(employeeDTO);

                if (result != null)
                {
                    return PartialView("Success");
                }
            }

            return PartialView(employee);
        }

        // GET: Employee/Edit/5
        public async Task<ActionResult> Edit(int id)
        {

            var employeeDTO = await _employeeServiceCRUD.GetByIdAsync(id);

            if (employeeDTO != null)
            {
                return PartialView(_mapper.Map<EmployeeDTO, EmployeeViewModel>(employeeDTO));
            }

            return PartialView(employeeDTO);
        }

        // POST: Employee/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FirstName,LastName,Patronymic,Age")] EmployeeViewModel employee)
        {
            if (ModelState.IsValid)
            {
                var employeeDTO = _mapper.Map<EmployeeViewModel, EmployeeDTO>(employee);
                _employeeServiceCRUD.UpdateAsync(employeeDTO);

                return PartialView("Success");
            }

            return PartialView(employee);
        }

        // GET: Employee/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            var employeeDTO = await _employeeServiceCRUD.GetByIdAsync(id);

            if (employeeDTO != null)
            {
                return PartialView("Delete", _mapper.Map<EmployeeDTO, EmployeeViewModel>(employeeDTO));
            }

            return PartialView(_mapper.Map<EmployeeDTO, EmployeeViewModel>(employeeDTO));
        }

        // POST: Employee/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            var employeeDTO = await _employeeServiceCRUD.DeleteAsync(id);

            if (employeeDTO != null)
            {
                return PartialView("Success");
            }

            return PartialView();
        }
    }
}

WebApp/Controllers/EmployeeStatisticsController.cs
using AOPenenzaTest.BLL.AbstractEmployeeService;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class EmployeeStatisticsController : Controller
    {
        private readonly IEmployeeStatisticsService  _employeeStatisticsService;

        public EmployeeStatisticsController(
            IEmployeeStatisticsService employeeStatisticsService)
        {
            _employeeStatisticsService = employeeStatisticsService;

        }

        // GET: EmployeeStatistics
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<JsonResult> GetStatistic(int type)
        {
            EmployeeStatisticType employeeStatisticType = (EmployeeStatisticType)type;

            if (employeeStatisticType == EmployeeStatisticType.AverageAge)
            {
                var result = await _employeeStatisticsService.GetAverageAgeAsync();
                return Json(String.Format("Средний возраст сотрудников: {0:f}", result),  JsonRequestBehavior.AllowGet);
            }
            else if(employeeStatisticType == EmployeeStatisticType.EmployeeCount)
            {
                var result = await _employeeStatisticsService.GetCountAsync();
                return Json($"Кол-во сотрудников: {result}", JsonRequestBehavior.AllowGet);
            }

            return Json("Error", JsonRequestBehavior.AllowGet);
        }
    }
}

WebApp/Views/Employee/Create.cshtml
@model WebApp.Models.EmployeeViewModel

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Сотрудник</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Patronymic, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Patronymic, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Patronymic, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10 col-md-offset-4">
                <input id="formButton" type="submit" value="Добавить" class="btn btn-default" />
                <input id="formButtonClose" type="submit" value="Отмена" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<script>
     $("#formButton").on("click", function (e) {
        e.preventDefault();
        $.ajax({
            url: "@Url.Action("Create")",
            type: "POST",
         data: $('form').serialize(),
            datatype: "json",
            success: function (result) {
            $("#dialogContent").html(result);
            }
        });
     });
    $("#formButtonClose").click(function(){
        $("#dialogContent").dialog().remove();
    });
</script>

WebApp/Views/Employee/Delete.cshtml
@model WebApp.Models.EmployeeViewModel

<div>
    <h4>Сотрудник</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Patronymic)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Patronymic)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

    <div class="form-group">
        <div class="col-md-10 col-md-offset-4">
            <input id="formButton" type="submit" value="Удалить" class="btn btn-default" />
            <input id="formButtonClose" type="submit" value="Отмена" class="btn btn-default" />
        </div>
    </div>
    }
</div>
<script>
    $("#formButton").on("click", function (e) {
        e.preventDefault();
        $.ajax({
            url: "@Url.Action("Delete"+ "/" + Model.Id)",
            type: "POST",
         data: $('form').serialize(),
            datatype: "json",
            success: function (result) {
            $("#dialogContent").html(result);
            }
        });
    });
    $("#formButtonClose").click(function(){
        $("#dialogContent").dialog().remove();
    });
</script>

WebApp/Views/Employee/Details.cshtml
@model WebApp.Models.EmployeeViewModel

<div>
    <h4>Сотрудник</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Patronymic)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Patronymic)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>

    </dl>
</div>
<div class="form-group">
    <div class="col-md-5 col-md-offset-5">
        <input id="formButtonClose" type="submit" value="Отмена" class="btn btn-default" />
    </div>
</div>
<script>
    $("#formButtonClose").click(function(){
        $("#dialogContent").dialog().remove();
    });
</script>

WebApp/Views/Employee/Edit.cshtml
@model WebApp.Models.EmployeeViewModel

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Сотрудник</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Patronymic, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Patronymic, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Patronymic, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10 col-md-offset-4">
                <input id="formButton" type="submit" value="Изменить" class="btn btn-default" />
                <input id="formButtonClose" type="submit" value="Отмена" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<script>
    $("#formButton").on("click", function (e) {
        e.preventDefault();
        $.ajax({
            url: "@Url.Action("Edit"+ "/" + Model.Id)",
            type: "POST",
         data: $('form').serialize(),
            datatype: "json",
            success: function (result) {
            $("#dialogContent").html(result);
            }
        });
    });
    $("#formButtonClose").click(function(){
        $("#dialogContent").dialog().remove();
    });
</script>

WebApp/Views/Employee/Index.cshtml
<div id="listContainer"></div>
@section scripts
{
    <script language="javascript" type="text/javascript">
        $(document).ready(function () {
            $("#listContainer").load('@Url.Action("List")'); // Загрузка частичного представления
        });
        function updateContent() {
            $.ajax({
                beforeSend: function () {
                    $("#loadingDiv").show();
                },
                url: $(this).attr("href"),
                type: 'GET',
                cache: false,
                success: function (result) {
                    $('#content').html(result);
                },
                complete: function () {
                    $("#loadingDiv").hide();
                }
            });
            return false;
        }
    </script>

}

WebApp/Views/Employee/List.cshtml
@model IEnumerable<WebApp.Models.EmployeeViewModel>
@{
    Layout = null;
}
<head>
    <title></title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/themes/base/all.css")" rel="stylesheet" type="text/css" />
</head>
<body>
    <div id="content">
        <h2>Сотрудники</h2>
        <br />      
        <br />
        <p>
            @Html.ActionLink(" ", "Create", new { }, new { @class = "viewDialog btn btn-default glyphicon glyphicon-plus", data_dialog_title = "Добавить" })
        </p>
        <table class="table table-bordered table-hover">
            <tr id="contentSorter">
                <th>
                    @Html.DisplayNameFor(model => model.FirstName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LastName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Patronymic)
                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.FirstName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LastName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Patronymic)
                    </td>

                    <td style="width: 150px;">
                        @Html.ActionLink(" ", "Details", new { id = item.Id },
                            new { @class = "viewDialog btn btn-default glyphicon glyphicon-exclamation-sign", data_dialog_title = "Просмотр" })
                        @Html.ActionLink(" ", "Edit", new { id = item.Id },
                            new { @class = "viewDialog btn btn-default glyphicon glyphicon-pencil", data_dialog_title = "Редактировать" })
                        @Html.ActionLink(" ", "Delete", new { id = item.Id },
                            new { @class = "viewDialog btn btn-default glyphicon glyphicon-minus", data_dialog_title = "Удалить" })
                    </td>
                </tr>
            }

        </table>
        <br />
    </div>
    <script src='@Url.Content("~/Scripts/jquery-3.2.1.min.js")' type="text/javascript"></script>
    <script src='@Url.Content("~/Scripts/jquery-ui-1.12.1.min.js")' type="text/javascript"></script>
    <script>
        $(document).ready(function () {
            $.ajaxSetup({ cache: false });
            $(".viewDialog").on("click", function (e) {
                e.preventDefault();
                $("<div id='dialogContent'></div>")
                    .addClass("modal-content")
                    .appendTo("body")
                    .load(this.href)
                    .dialog({
                        open: function (event, ui) {
                            $(".ui-dialog-titlebar-close", ui.dialog | ui).hide();
                        },
                        show: { effect: "blind", duration: 200 },
                        hide: { effect: "blind", duration: 200 },
                        Height: 'auto',
                        minWidth: '600',
                        resizable: false,
                        position: { my: "center top", at: "center top - 100", of: ".table" },
                        title: $(this).attr("data-dialog-title"),
                        close: function () { $(this).remove() },
                        modal: true
                    });
            });          
        });
    </script>
</body>

WebApp/Views/Employee/Success.cshtml
<h2 class="text-info text-center">Успешно</h2>
<script>
    $(document).ready(function () {
        setTimeout(function () {
            $("#dialogContent").dialog().dialog("close");
            updateContent();
        }, 300);
    })
    function updateContent() {
        $.ajax({
            beforeSend: function () {
                $("#loadingDiv").show();
            },
            url: "@Url.Action("List")",
            type: 'GET',
            cache: false,
            success: function (result) {
                $('#content').html(result);
            },
            complete: function () {
                $("#loadingDiv").hide();
            }
        });
        return false;
    }
</script>

WebApp/Views/EmployeeStatistics/Index.cshtml
@{
    ViewBag.Title = "Статистика";
}
<head>
    <title></title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/themes/base/all.css")" rel="stylesheet" type="text/css" />
</head>
<body>
    <br />
    <h2>Статистика</h2>
    <form id="actionForm" action="@Url.Action("GetStatistic")" method="get" class="form-inline">
        <div class="form-group">
            <select name="type" size="1">
                <option value="1" selected="selected">Кол-во сотрудников</option>
                <option value="2">Средний возраст сотрудников</option>
            </select>
        </div>
        <button type="submit" value="Odsfsdfk" class="btn btn-default glyphicon glyphicon-search"></button>
    </form>
    <br />
    <h2 id="content"></h2>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script>

        $(document).ready(function () {
            $("#actionForm").submit(function (event) {
                event.preventDefault();
                $.ajax({
                    beforeSend: function () {
                        $("#loadingDiv").show();
                    },
                    url: $("#actionForm").attr('action'),
                    data: $("#actionForm").serialize(),
                    type: 'GET',
                    cache: false,
                    success: function (data) {
                        $('#content').text(data);
                    },
                    complete: function () {
                        $("#loadingDiv").hide();
                    }
                });
            });
        });
    </script>
</body>

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - AO Penenza</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/loaderstyle.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div id="loadingDiv" class="loader"></div>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Сотрудники", "Index", "Employee", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Статистика", "Index", "EmployeeStatistics", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav"></ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - AO Penenza</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>